function textbox = popup(input, fig)
% popup function displays a pop-up message in a figure.
% (By Lisa Thelen and Lizzy Da Rocha Bazilio)

message = sprintf(input);
textbox = annotation(fig,'textbox',...
    'String', message,...
    'FontSize', 20,...
    'Position',[.3 .3 .4 .4],...
    'HorizontalAlignment', 'center',...
    'VerticalAlignment', 'middle');
end 

